name: poteu_local_storage_repository
description: A repository that handles poteu local storage related requests.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  poteu_api:
    path: ../poteu_api

dev_dependencies:
  very_good_analysis: ^2.4.0


