name: tts
description: A Flutter implementation of the tts that uses tts.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^3.5.0

  tts_api:
    path: ../tts_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.4.0
